# Generated by Django 2.0.1 on 2018-01-25 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feedback.User'),
            preserve_default=False,
        ),
    ]
