# Generated by Django 2.0.1 on 2018-01-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='links',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='of_class',
        ),
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='links',
            field=models.ManyToManyField(to='study_material.Link'),
        ),
        migrations.AddField(
            model_name='subject',
            name='of_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_material.Class'),
        ),
    ]
